<nav class="top-nav" style="display: flex; align-items: center;">
        <div class="icon">
            <img src="images/earth-americas-solid-full.svg" alt="icon of globe">
        </div>
    
        <p class="top-nav-text australia">Australia</p>
    
        <span class="top-nav-text">Are you an <a href="" class="hyperlink">employer?</a></span>
    
    
        <span class="top-nav-text top-nav-text2">Perhaps a <a href="" class="hyperlink">candidate?</a><button
                class="apply-button"> Apply now</button></span>
    
        <div class="icon-tray">
            <div class="icon">
                <img src="images/facebook-brands-solid-full.svg" alt="facebook icon">
            </div>
            <div class="icon">
                <img src="images/linkedin-brands-solid-full.svg" alt="Linkdin icon">
            </div>
            <div class="icon">
                <img src="images/square-instagram-brands-solid-full.svg" alt="Instagram icon">
            </div>
            <div class="icon">
                <img src="images/door-open-solid-full.svg" alt="Exit icon">
            </div>
        </div>
    </nav>