      <footer>
        <section class="ending-section">
            <div class="ending-container">
                <div class="ending-container-left-part">
                    <div class="company-logo">
                        <img src="assets/niwslogonb.png" alt="icon of globe">
                    </div>

                    <p class="site-title ending-title">N I W S</p>
                </div>
                <p class="repo-text">Github link: <a href="https://github.com/Emajaliwa/RecruitmentWebsite.git"
                        class="hyperlink">Click here!</a></p>
                <p class="repo-text">Jira link: <a
                        href="https://student-team-kig7i9hh.atlassian.net/issues/?jql=assignee+%3D+currentUser%28%29+AND+statusCategory+%21%3D+done+AND+due+%3C%3D+2025-09-16+AND+due+%3E%3D+2025-09-09&atlOrigin=eyJpIjoiOGIzN2RkMTlkNmEyNDYyYzhiYTc0MGZlNmMxOGU0YzgiLCJwIjoiaiJ9"
                        class="hyperlink">To Jira!</a></p>

                <p class="repo-text">Company email: <a href="mailto:info@niws.com" class="hyperlink">info@niws.com</a>
                </p>





            </div>





        </section>


    </footer>