 <nav class="nav-bar">

            <div style="display: flex; align-items: center;">
                <div class="company-logo">
                    <img src="assets/niwslogonb.png" alt="icon of globe">
                </div>

                <p class="site-title">N I W S</p>
            </div>

            <div style="display: flex; align-items: center;">
                <ul class="nav-list">
                    <li><a href="index.php">Home</a></li>
                    <li><a href="jobs.php">Jobs</a></li>
                    <li><a href="about.php">About</a></li>
                    <li><a href="apply.php">Apply</a></li>
                    <li><a href="manage.php">Admin</a></li>
                </ul>

                <div class="nav-menu">
                    <img src="assets/bars-solid-full.svg" alt="menu icon">
                </div>

            </div>

        </nav>